jobs:
  changes:
    name: Check README and metadata format for changed files
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: file_changes
      name: Detect changed file paths
      uses: trilom/file-changes-action@master
    - continue-on-error: true
      name: Checkout the repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Print changed file paths
      run: 'echo ''Below shows a list of changed file paths''

        echo ''${{ steps.file_changes.outputs.files}}''

        '
    - continue-on-error: true
      name: Run style checks
      uses: ./tools/CI/README_Metadata_StyleCheck
      with:
        FILE_PATHS: ${{ steps.file_changes.outputs.files }}
name: README and metadata formatting
on:
  repository_dispatch:
    types: trigger-ga___main.yml
